run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
        - errcheck
        - gosec

go:
  gover: "1.21"
